### PR TITLE
Allow access to dict methods in OrderedDict

### PR DESCRIPTION
**Pull request by petebrowne**
See #2

### CODE REVIEW

**Comment by joeljames** [comment]
👍

**Comment by petebrowne** [comment]
Can you release this when you get a chance?

**Review by reneric — COMMENTED** [review]
👍

**Comment by joeljames** [comment]
@petebrowne  Thanks for the PR. I have bumped the version and pushed up to pypi https://pypi.python.org/pypi/pysharedutils/0.4.1

**Comment by petebrowne** [comment]
Thanks!

**Pull request merged**
